### ISSUE TITLE
Add support for ROUTE

### ISSUE THREAD

**Issue by rickpayne** [ypo/flute#25]
I was trying to decode some ROUTE (RFC 9223) which is pretty similar to FLUTE, but hit the lack of support for Codepoint 8. I'm wondering if you have any thoughts about adding ROUTE support to this crate?

**Comment by ypo** [comment]
You’re correct, this library currently does not support ROUTE.

Since ROUTE is based on FLUTE, I’m open to adding some support for decoding ROUTE sessions to this FLUTE library. 
However, I don’t have an immediate timeline for implementing this feature.

codepoint field has a different meaning in ROUTE compared to FLUTE:

- In FLUTE, the codepoint represents the FEC Encoding ID.
- In ROUTE, the codepoint indicates the type of payload (e.g., Media Segment).

Would you be able to share a pcap file with ROUTE so I can use it for testing ?

**Comment by ypo** [comment]
Thanks for the sharing,

I did have a look to the short capture, 
I could not find a way to detect that ALC packets are ROUTE and not FLUTE, so from my understanding it will necessary to configure the decoder with a parameter informing it's a ROUTE session.

I'm afraid that today I don't know the ROUTE protocol well enough to add the support. So I prefer to keep the focus on FLUTE (part of DVB-NIP)

**Comment by ypo** [comment]
I'm testing a few fixes in my local build to check if I can successfully decode your stream, I'll let you know about the result

**Comment by ypo** [comment]
After a more detailed review, I have decided not to integrate ROUTE support into this FLUTE library. There are several reasons for this decision:

- Incompatibility: ROUTE and FLUTE have slightly different definitions, making them not directly compatible.
- Detection Issues: There is no way to detect if an ALC/LCT packet is ROUTE or FLUTE.
- Decoding Differences: There are several differences in decoding noCode objects, such as Source Offset vs. SBN/ESI.
- Media-Aware Packetization: ROUTE uses media-aware packetization, whereas I prefer to keep this library application-independent, as it is for FLUTE.

Thanks again for you sharing, that was helpful,

I believe that having an open-source ROUTE implementation in Rust would be great. However, it should be developed as a separate crate.
